config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new'
  post '/users', to: 'users#create'

  get '/interests', to: 'interests#index'
  post '/interests', to: 'interests#create'
  delete '/interests/:id', to: 'interests#destroy', as: :interest

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interest.rb
class Interest < ApplicationRecord
  validates_presence_of :name
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :username
  validates :password, :presence => true, :on => :create
  validates :password, confirmation: {case_sensitive: true}
  validates :email, presence: true, uniqueness: true

  has_secure_password
  has_many :interests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController

  def index
    if current_user
      @interests = Interest.where(user: current_user)
      @interest = Interest.new
    else
      redirect_to '/login', notice: "You must log in first"
    end
  end

  def create
    user = current_user
    interest = user.interests.new(interest_params)
    if interest.save
      redirect_to '/interests', notice: "#{params[:interest][:name].titleize} has been successfully added"
    else
      redirect_to '/interests', notice: "Something went wrong. Try Again"
    end
  end

  def destroy
    interest = Interest.find_by_id(params[:id])
    interest.delete
    redirect_to '/interests', notice: "#{interest.name.titleize} has been successfully deleted"
  end

  private

  def interest_params
    params.require(:interest).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to root_path, notice: "You are already logged in"
    end
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Hi, #{user.username}!"
    else
      redirect_to login_path, notice: "Password does not match username. Please try again."
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path, notice: "You have successfully logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    unless current_user
      @user = User.new
    else
      redirect_to root_path, notice: "You are already logged in"
    end
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Please complete all fields and enter a unique email address"
      redirect_to register_path
    end
  end
  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user && params[:inspire]
      @facade = RecommendationFacade.new(current_user)
    elsif !current_user
      redirect_to '/login', notice: "You must log in first"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/interests/index.html.erb
<div class="center">
  <h2>My Interests</h2>
  <div class="interests">
    <% @interests.each do |interest| %>
    <div class="interest" id="interest-<%= interest.id %> ">
      <div class="interest-name"><%= interest.name %></div>
      <div class="interest-x" id="delete-interest-<%=interest.id%>">
        <%= button_to "X", interest_path(id: interest.id), method: :delete, class:"interest-submit" %>
      </div>
    </div>
    <% end %>
  </div>
  <%= form_for @interest do |f| %>
  <%= f.text_field :name, placeholder: "Add Interest", class:"add-field" %>
  <%= f.submit "+", class:"add-button" %>
  <% end %>

  <%= link_to "< Back", root_path, class:"page-link" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inspire</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1 class="title">INSPIRE</h1>
    <div class='flash'>
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: name %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class='form'>
  <h2>New User Registration</h2>
  <%= form_for @user do |f| %>
  <div class="form-entry">
    <%= f.label :email, class:"form-label"%>
    <%= f.text_field :email, class:"form-field" %>
  </div>
  <div class="form-entry">
    <%= f.label :username, class:"form-label" %>
    <%= f.text_field :username, class:"form-field" %>
  </div>
  <div class="form-entry">
    <%= f.label :password, class:"form-label" %>
    <%= f.password_field :password, class:"form-field" %>
  </div>
  <div class="form-entry">
    <%= f.label :password_confirmation, class:"form-label" %>
    <%= f.password_field :password_confirmation, class:"form-field" %>
  </div>

    <%= f.submit "Create Account", class:"form-submit" %>
  <% end %>
  <%= link_to "Back to Login", login_path, class:"page-link"%>
</div>

app/views/welcome/index.html.erb
<div class="center">
  <%= link_to "Inspire me!", root_path(inspire: true), class:"inspire"%>
  <div class="rec-container">
    <% if @facade %>
    <div class="recommendation">
      <% unless @facade.error %>
        <h2 class="how-about">How about...</h2>
        <h3 class="recommendation-name"><%= @facade.rec_name %></h3>
        <h4 class="recommendation-type">Type: <%= @facade.rec_type %></h4>
        <p class="recommendation-teaser"><%= @facade.rec_teaser %></p>
      <% else %>
        <p><%= @facade.error %></p>
      <% end %>
    </div>
    <% end %>
  </div>
  <div class="lower-links">
    <%= link_to "My Interests", interests_path, class:"page-link" %><br />
    <%= link_to "Log Out", logout_path, method: :delete, class:"page-link" %>
  </div>

</div>